{
    "name": "Deploy website",
    "on": {
        "schedule": {
            "cron": "35 * * * *", # hourly
        },
    },
    "jobs": {
        "deploy": {
            "name": "Build and deploy",
            "timeout-minutes": 5,
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "name": "Checkout current repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "fetch-depth": 1,
                    },
                },
                {
                    "name": "Checkout documentation repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "repository": "RobloxAPI/doc",
                        "fetch-depth": 1,
                        "ref": "master",
                        "path": ".deploy/doc",
                    },
                },
                {
                    "name": "Checkout website repository",
                    "uses": "actions/checkout@v1",
                    "with": {
                        "repository": "RobloxAPI/ref",
                        "fetch-depth": 1,
                        "ref": "gh-pages",
                        "path": ".deploy/robloxapi.github.io/ref",
                    },
                },
                {
                    "name": "Generate module",
                    "run": "go mod init github.com/robloxapi/rbxapiref",
                },
                {
                    "name": "Get dependencies",
                    "run": "go get -v -d ./...",
                },
                {
                    "name": "Compile executable",
                    "run": "go build -v .",
                },
                {
                    "name": "Rebuild website",
                    "run": "./rbxapiref -s .github/settings.json",
                },
                {
                    "name": "Commit and deploy website",
                    "run": "
                        pushd ../.deploy/robloxapi.github.io/ref &&
                        git config user.email 'anaminus@protonmail.com' &&
                        git config user.name 'Anaminus' &&
                        git add -A &&
                        git commit -m 'Update reference.' &&
                        git push origin gh-pages &&
                        popd
                    ",
                },
            ],
        },
    },
}
